version: 2.1
orbs:
  node: circleci/node@4.7.0
  
jobs:
  test:
    parameters:
      directory:
        type: string
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: <<parameters.directory>>
          cache-version: <<parameters.directory>>-1
      - run:
          command: npm run lint
          name: Run linter
          working_directory: <<parameters.directory>>
      - run:
          command: npm run ci:test
          name: Run tests
          working_directory: <<parameters.directory>>
  deploy:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: test-runner
          cache-version: test-runner-1
      - run:
          name: Remove cached package link from node/install-packages
          command: unlink /tmp/node-project-lockfile
      - node/install-packages:
          app-dir: package
          cache-version: package-1
      - run:
          name: Build UI
          command: ./build.sh
          working_directory: test-runner
      - run:
          name: Build UI
          command: npm build
          working_directory: package
      - run:
          name: Semantic Version
          command: npx semantic-release
          working_directory: package




workflows:
  on_commit:
    jobs:
      - test:
          name: "Package Tests"
          directory: "package"
      - test:
          name: "Test Runner Tests"
          directory: "test-runner"
      - deploy:
          requires:
            - "Package Tests"
            - "Test Runner Tests"
          filters:
            branches:
              only: fix-deploy