version: 2.1
orbs:
  node: circleci/node@4.7.0
  
jobs:
  test:
    parameters:
      directory:
        type: string
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: <<parameters.directory>>
          cache-version: <<parameters.directory>>-1
      - run:
          command: npm run lint
          name: Run linter
          working_directory: <<parameters.directory>>
      - run:
          command: npm run ci:test
          name: Run tests
          working_directory: <<parameters.directory>>
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run:
          name: Build UI
          command: ./build.sh
          working_directory: test-runner
      - run:
          name: Build UI
          command: npm build
          working_directory: package
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
          working_directory: package
      - attach_workspace:
          at: ~/repo



workflows:
  on_commit:
    jobs:
      - test:
          name: "Package Tests"
          directory: "package"
      - test:
          name: "Test Runner Tests"
          directory: "test-runner"
  on_tag:
    jobs:
      - test:
          name: "Package Tests"
          directory: "package"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          name: "Test Runner Tests"
          directory: "test-runner"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - "Package Tests"
            - "Test Runner Tests"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/